include(
    ":app",
    ":ui-common-compose",
    ":ui-movie",
    ":ui-profile",
    ":themdb-api",
    ":ui-common-resources",
    ":base",
    ":ui-login",
    ":ui-tab-host",
    ":coil-image",
    ":ui-tv",
)